FROM openjdk:11-buster
LABEL maintainer="pfeil@.kit.edu"

ARG SERVICE_FOLDER
ARG BINARY_NAME
ENV SERVICE_FOLDER=${SERVICE_FOLDER}
ENV BINARY_NAME=${BINARY_NAME}

RUN apt-get update && \
    apt-get upgrade --assume-yes && \
    apt-get install --assume-yes git && \
    mkdir -p /var/repository && \
    mkdir -p /kitdm20/${SERVICE_FOLDER}/release

COPY java-release-run.sh /kitdm20/
COPY $SERVICE_FOLDER/conf/application.properties /kitdm20/$SERVICE_FOLDER/release/config/application.properties
COPY bin/${BINARY_NAME}.jar /kitdm20/${SERVICE_FOLDER}/release/

EXPOSE 8080
CMD bash /kitdm20/java-release-run.sh $SERVICE_FOLDER $BINARY_NAME
